name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3']
        rails-version: ['7.0', '7.1', '8.0']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Set up Rails ${{ matrix.rails-version }}
      run: |
        export RAILS_VERSION=${{ matrix.rails-version }}
        bundle update

    - name: Run tests
      run: bundle exec rake test

    - name: Run RuboCop
      run: bundle exec rubocop

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Run bundle audit
      run: |
        gem install bundler-audit
        bundle audit --update